# Generated by Django 4.2.16 on 2024-12-05 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title of the project')),
                ('description', models.TextField(verbose_name='description of the project')),
                ('goal_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='goal amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('failed', 'Failed')], default='open', max_length=10, verbose_name='status')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='crowdfundin_created_3e5e87_idx'), models.Index(fields=['status'], name='crowdfundin_status_02ba67_idx')],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=100, verbose_name='donor name')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='crowdfunding.project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'donation',
                'verbose_name_plural': 'donations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='crowdfundin_created_fe6b6a_idx')],
            },
        ),
    ]
