# Generated by Django 4.2.16 on 2024-12-05 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[('art', 'Art'), ('technology', 'Technology'), ('education', 'Education'), ('health', 'Health')], default='technology', max_length=20, null=True, verbose_name='category'),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='slug'),
        ),
    ]
