# Generated by Django 4.2.16 on 2024-12-05 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0002_project_category_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('art', 'Art'), ('technology', 'Technology'), ('education', 'Education'), ('health', 'Health')], default='technology', max_length=20, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(default=1, unique=True, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
